[features]
seeds = false
skip-lint = false
[programs.localnet]
wu_pay_spl = "HnHcveP6wj7wV1vwcXEHCm7792P2b6fr6VqGjB1yVWfv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lebingxie/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
